# Generated by Django 3.2.5 on 2021-07-23 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('aisle', models.CharField(max_length=60)),
                ('shelf', models.CharField(max_length=60)),
                ('column', models.CharField(max_length=60)),
                ('row', models.CharField(max_length=60)),
                ('medications', models.ManyToManyField(to='myapi.Medication')),
            ],
        ),
    ]
